// AUTO-GENERATED by scraper — do not edit by hand
// Scraped 2026-09-25 · markup UGX 5000
var SCRAPED_PRODUCTS = [
 {
  "id": "sc-raspberry-pi-4b-4gb",
  "cat": "boards",
  "emoji": "🤖",
  "name": "Raspberry Pi 4B 4GB",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 625000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-raspberry-pi-4b-8gb",
  "cat": "boards",
  "emoji": "🤖",
  "name": "Raspberry Pi 4B 8GB",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 645000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-raspberry-pi-4b-2gb",
  "cat": "boards",
  "emoji": "🤖",
  "name": "Raspberry Pi 4B 2GB",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 485000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-raspberry-pi-3b-",
  "cat": "boards",
  "emoji": "🤖",
  "name": "Raspberry Pi 3B+",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 325000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-raspberry-pi-compute-mo-",
  "cat": "boards",
  "emoji": "🤖",
  "name": "Raspberry Pi Compute Mo...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 390000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-raspberry-pi-pico-wh",
  "cat": "boards",
  "emoji": "🤖",
  "name": "Raspberry Pi Pico WH",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 45000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-raspberry-pi-pico-h",
  "cat": "boards",
  "emoji": "🤖",
  "name": "Raspberry Pi Pico H",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 35000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-raspberry-pi-400-kit",
  "cat": "boards",
  "emoji": "🤖",
  "name": "Raspberry Pi 400 Kit",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 590000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-arduino-nano-33-iot",
  "cat": "boards",
  "emoji": "🤖",
  "name": "Arduino Nano 33 IoT",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 185000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-arduino-nano-every-ori-",
  "cat": "boards",
  "emoji": "🤖",
  "name": "Arduino Nano Every (Ori...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 85000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-arduino-nano",
  "cat": "boards",
  "emoji": "🤖",
  "name": "Arduino nano",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 40000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-texas-instrument-s-msp4-",
  "cat": "components",
  "emoji": "🔌",
  "name": "Texas Instrument's MSP4...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 125000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-sim800l-gsm-modem-impr-",
  "cat": "components",
  "emoji": "🔌",
  "name": "SIM800L GSM Modem (Impr...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 55000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-gy-neo6mv2-gps-modem",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "GY-NEO6MV2 GPS Modem",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 35000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-nrf24l01",
  "cat": "components",
  "emoji": "🔌",
  "name": "NRF24L01",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 15000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-lm2596-dc-dc-3-35v-adju-",
  "cat": "power",
  "emoji": "🔋",
  "name": "LM2596 DC-DC 3-35V ADJU...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 15000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-16x2-lcd-module-white-b-",
  "cat": "components",
  "emoji": "🔌",
  "name": "16x2 LCD module white/b...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 25000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-e32-433t30d-lora-433mh-",
  "cat": "components",
  "emoji": "🔌",
  "name": "E32-433T30D Lora (433MH...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 85000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-e22-900t22d-868mhz-lora-",
  "cat": "components",
  "emoji": "🔌",
  "name": "E22-900T22D 868MHz Lora...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 55000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-dht11-sensor-module",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "DHT11 sensor Module",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 15000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-tmp36gt9z-temperature-s-",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "TMP36GT9Z Temperature s...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 20000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-submersible-temperature-",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "Submersible Temperature...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 17000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-arduino-soil-moisture-s-",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "Arduino soil moisture s...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 15000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-lm35-analog-temperature-",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "LM35 Analog temperature...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 20000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-bme280-atmospheric-pres-",
  "cat": "components",
  "emoji": "🔌",
  "name": "BME280 Atmospheric Pres...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 20000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-bmp180-barometric-press-",
  "cat": "components",
  "emoji": "🔌",
  "name": "BMP180 Barometric Press...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 20000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-raspberry-pi-rp2040",
  "cat": "boards",
  "emoji": "🤖",
  "name": "Raspberry Pi RP2040",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 9000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-case-for-raspberry-pi-4-",
  "cat": "boards",
  "emoji": "🤖",
  "name": "Case for Raspberry Pi 4...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 35000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-raspberry-pi-camera-mod-",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "Raspberry Pi Camera Mod...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 185000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-raspberry-pi-5-8gb",
  "cat": "boards",
  "emoji": "🤖",
  "name": "Raspberry Pi 5 - 8GB",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 865000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-official-raspberry-pi-4-",
  "cat": "boards",
  "emoji": "🤖",
  "name": "Official Raspberry Pi 4...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 60000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-infrared-temperature-se-",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "Infrared Temperature Se...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 55000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-pir-motion-sensor-modul-",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "PIR Motion sensor modul...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 20000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-mq-4-methane-biogas-sen-",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "MQ-4 Methane/Biogas sen...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 20000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-mq-5-gas-sensor-lpg-n-",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "MQ-5 gas sensor (LPG, n...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 20000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-color-sensor-module-tsc-",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "Color Sensor Module TSC...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 50000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-infrared-receiver-vs183-",
  "cat": "components",
  "emoji": "🔌",
  "name": "Infrared Receiver VS183...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 7000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-sn74ls47-common-anode-7-",
  "cat": "components",
  "emoji": "🔌",
  "name": "SN74LS47 Common Anode 7...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 8000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-raspberry-pi-5-4gb-ram",
  "cat": "boards",
  "emoji": "🤖",
  "name": "Raspberry Pi 5 4GB RAM",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 555000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-water-flow-sensor-flo-",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "Water Flow Sensor / Flo...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 55000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-atmega328p-microcontrol-",
  "cat": "boards",
  "emoji": "🤖",
  "name": "Atmega328P microcontrol...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 22000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-pic18f4550-microcontr-",
  "cat": "boards",
  "emoji": "🤖",
  "name": "PIC18F4550 microcontr...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 45000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-atmega32a-microcontroll-",
  "cat": "boards",
  "emoji": "🤖",
  "name": "ATMEGA32A Microcontroll...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 35000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-msp430g553-microcontrol-",
  "cat": "boards",
  "emoji": "🤖",
  "name": "MSP430G553 Microcontrol...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 25000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-raspberry-pi-5-official-",
  "cat": "boards",
  "emoji": "🤖",
  "name": "Raspberry Pi 5 Official...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 55000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-16mhz-crystal-oscillato-",
  "cat": "components",
  "emoji": "🔌",
  "name": "16MHz crystal oscillato...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 7500,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-esp32-wifi-cam-with-ov2-",
  "cat": "boards",
  "emoji": "🤖",
  "name": "ESP32 wifi CAM with OV2...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 55000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-ssd1306-0-96-oled-blue",
  "cat": "components",
  "emoji": "🔌",
  "name": "SSD1306 0.96\" OLED Blue",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 30000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-ft232rl-ft232-ftdi-usb-",
  "cat": "components",
  "emoji": "🔌",
  "name": "FT232RL FT232 FTDI USB...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 20000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-male-header-2-54mm-pitc-",
  "cat": "power",
  "emoji": "🔋",
  "name": "Male header 2.54mm pitc...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 6000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-female-header-2-54mm-pi-",
  "cat": "power",
  "emoji": "🔋",
  "name": "Female header 2.54mm pi...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 6500,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-3-3v-5v-graphic-display-",
  "cat": "components",
  "emoji": "🔌",
  "name": "3.3V/5V Graphic Display...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 55000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-lcd-20x4-character-modu-",
  "cat": "components",
  "emoji": "🔌",
  "name": "LCD 20x4 Character Modu...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 35000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-blue-3-pin-screw-termin-",
  "cat": "components",
  "emoji": "🔌",
  "name": "Blue 3-Pin Screw Termin...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 7500,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-esp32-esp-32-wroom-wifi-",
  "cat": "boards",
  "emoji": "🤖",
  "name": "ESP32 ESP-32 WROOM WiFi...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 65000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-nodemcu-esp8266-esp-12e-",
  "cat": "boards",
  "emoji": "🤖",
  "name": "NodeMCU ESP8266 ESP-12E...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 55000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-pcf8574-i2c-lcd-module",
  "cat": "components",
  "emoji": "🔌",
  "name": "PCF8574 I2C LCD MODULE",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 11000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-acs712t-5a-current-sens-",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "ACS712T 5A Current Sens...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 25000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-acs712-20a-current-sens-",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "ACS712 20A current sens...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 25000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-as608-fingerprint-reade-",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "AS608 Fingerprint reade...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 85000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-hc-sr04-ultrasonic-dist-",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "HC-SR04 ultrasonic dist...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 17000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-mq-2-lpg-smoke-sensor",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "MQ-2 LPG/Smoke sensor",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 20000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-mq-3-alcohol-sensor-mod-",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "MQ-3 Alcohol Sensor Mod...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 20000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-mq-7-carbon-monoxide-ga-",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "MQ-7 Carbon Monoxide Ga...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 20000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-mq-135-air-quality-sens-",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "MQ-135 Air Quality sens...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 20000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-mq6-gas-sensor",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "MQ6 Gas sensor",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 20000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-ky-033-infrared-line-tr-",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "KY-033 Infrared line tr...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 13000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-mc38-door-close-sensor",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "MC38 door close sensor",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 15000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-water-level-sensor-fl-",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "Water level Sensor – Fl...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 40000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-mg811-carbon-dioxide-co-",
  "cat": "components",
  "emoji": "🔌",
  "name": "MG811 Carbon Dioxide CO...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 255000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-22pf-ceramic-capacitor",
  "cat": "components",
  "emoji": "🔌",
  "name": "22pF ceramic capacitor",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 5500,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-mfrc-522-rc522-rfid-s-",
  "cat": "sensors",
  "emoji": "👁️",
  "name": "MFRC-522 RC522 RFID + S...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 25000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-arduino-mega2560-develo-",
  "cat": "boards",
  "emoji": "🤖",
  "name": "Arduino Mega2560 Develo...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 85000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 },
 {
  "id": "sc-hdc-3-24v-high-decibel-",
  "cat": "components",
  "emoji": "🔌",
  "name": "HDC 3-24V High Decibel...",
  "desc": "Sourced from Neriko Electronics. Delivery arranged via MiniMakers.",
  "price": 9000,
  "source": "Neriko Electronics",
  "link": "https://nerikoelectronics.com/products"
 }
];
